### ISSUE TITLE
在面包屑中使用TransitionGroup似乎没有效果

### ISSUE THREAD

**Issue by init-center** [TuSimple/naive-ui#1648]
### TuSimple/naive-ui version (版本)
2.21.0

### Vue version (Vue 版本)
3.2.22

### Browser and its version (浏览器及其版本)
Chrome(96.0.4664.45)

### System and its version (系统及其版本)
Windows(10)

### Reappearance link (重现链接)
https://codesandbox.io/s/gallant-danny-duvfl?file=/src/App.vue

### Reappearance steps (重现步骤)
修改数据后面包屑后没有动画

### Expected results (期望的结果)
动画正常显示

### Actual results (实际的结果)
TransitionGroup无效，没有产生动画

**Comment by 07akioni** [comment]
这我还真不知道，不过感觉这个和组件库关系不大，可能是 transition group 的使用问题。

如果你发现这个和组件库的实现有关系，可以补充一些信息，我会重新打开这个 issue。

**Comment by pengxiaotian** [comment]
我试着替换成 `element-plus` 的 `el-breadcrumb`，是可以产生动画效果的

**Comment by pengxiaotian** [comment]
> 这我还真不知道，不过感觉这个和组件库关系不大，可能是 transition group 的使用问题。
> 
> 如果你发现这个和组件库的实现有关系，可以补充一些信息，我会重新打开这个 issue。

会不会是使用了 `tsx` 导致的。。

**Comment by 07akioni** [comment]
> > 这我还真不知道，不过感觉这个和组件库关系不大，可能是 transition group 的使用问题。
> > 如果你发现这个和组件库的实现有关系，可以补充一些信息，我会重新打开这个 issue。
> 
> 会不会是使用了 `tsx` 导致的。。

我觉得可能性不大，产生不了可能和样式有关系，比如 naive 用的是 `ul` 和 `li`。

**Comment by pengxiaotian** [comment]
vue 官网用的就是 `ul` `li` 示例。 但是我又试了其他几个库 如 `element-plus` 都是可以的。。无语了

**Comment by pengxiaotian** [comment]
> 这我还真不知道，不过感觉这个和组件库关系不大，可能是 transition group 的使用问题。
> 
> 如果你发现这个和组件库的实现有关系，可以补充一些信息，我会重新打开这个 issue。

我想我发现问题了：

```css
.n-breadcrumb-item {
  display: inline-flex;
  transition: color .3s var(--n-bezier);
  // ...
}
// 改为
.n-breadcrumb-item {
  display: inline-block;
  // ...
}
```
