### ISSUE TITLE
Add global css variables with a specific prefix

### ISSUE THREAD

**Issue by gzf6** [TuSimple/naive-ui#411]
### This function solves the problem (这个功能解决的问题)
We can change the theme style by overriding global variables. We can modify the theme only through the css file, without having to configure it in js.In this way, we can easily modify the theme dynamically by modifying the class name.
### Expected API (期望的 API)
naive-ui global css variables:
```css
--n-color-primary: green;
```

project css file:
```css
.theme-light {
    --n-color-primary: green;
}

.theme-dark {
    --n-color-primary: blue;
}
```
