### ISSUE TITLE
add -class where there is -style props (e.g. n-drawer body-content-style add body-content-class)

### ISSUE THREAD

**Issue by wc-matteo** [TuSimple/naive-ui#504]
### This function solves the problem (这个功能解决的问题)
helps styling with classes (e.g. tailwind user)
### Expected API (期望的 API)
add -class where there is -style props

**Comment by Volankey** [comment]
You can add classes like following code:
`<n-drawer v-model:show="show" :width="502" class="drawer-custom-class">`
```scss
.drawer-custom-class{
 :deep(n-drawer-body-content-wrapper){
    background:red;
 }
}
```
