### ISSUE TITLE
在浏览器跑耗时的程序的时候, spin不旋转

### ISSUE THREAD

**Issue by aixia715** [TuSimple/naive-ui#705]
### TuSimple/naive-ui version (版本)
2.14.0

### Vue version (Vue 版本)
3.2.0-beta.6

### Browser and its version (浏览器及其版本)
Microsoft Edge 92.0.902.55

### System and its version (系统及其版本)
Win10

### Reappearance link (重现链接)
https://codesandbox.io/s/priceless-cohen-fim55?file=/src/Demo.vue

### Reappearance steps (重现步骤)
点击"点击查看卡顿"按钮

### Expected results (期望的结果)
在浏览器跑耗时的程序的时候, spin旋转

### Actual results (实际的结果)
在浏览器跑耗时的程序的时候, spin不旋转.

### Remarks (补充说明)
怀疑是由于spin的旋转需要浏览器定时运行代码重新渲染, 考虑到使用spin的场景有很多是浏览器运行耗时的程序, 是否可以采用css动画的方式?

**Comment by 07akioni** [comment]
JS 执行会阻塞 UI 渲染，这个我们控制不了。

需要注意的是，使用 Spin 的场景是“异步”程序，而不是 CPU 密集的耗时程序。

**Comment by aixia715** [comment]
是否可以考虑使用CSS的方式? 如此在异步和CPU 密集的耗时程序都可以正常工作

**Comment by 07akioni** [comment]
> 是否可以考虑使用CSS的方式? 如此在异步和CPU 密集的耗时程序都可以正常工作

CSS 也不行的，你可以了解一下相关的信息。

**Comment by aixia715** [comment]
我自己写了个CSS的旋转动画用来解决这个问题

```html
<div class="waiting_donut"></div>
```

```css
.waiting_donut {
  display: block;
  position: fixed;
  border: 4px solid rgba(255, 255, 255, 0.4);
  border-left-color: rgb(0, 150, 136);
  border-radius: 50%;
  width: 50px;
  height: 50px;
  top: 50%;
  left: 50%;
  animation: donut_spin 1.2s linear infinite;
}

@keyframes donut_spin {
  0% {
    transform: translateX(-50%) translateY(-50%) rotate(0deg);
  }

  100% {
    transform: translateX(-50%) translateY(-50%) rotate(360deg);
  }
}
```
